### ISSUE TITLE
Consider renaming to ckeditor5-paste-from-office

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-paste-from-office#6]
"Office" is more generic than "Word" and we will want to add support for pasting from Excel, Outlook or PowerPoint. However, we'd also like to work on things like pasting from Google Docs or Libre Office, which are not Office apps. So is it worth using the word "Office" if it's still not generic enough when people know "paste from Word" already? Couldn't we do everything under "paste from Word"?

**Comment by Reinmar** [comment]
cc @wwalc @AnnaTomanek

**Comment by f1ames** [comment]
I think there was similar discussion in the CKEditor4 🤔 I think that is worth considering especially if we plan to support other Office products or Google Docs, Libre Office, etc.

Maybe to broaden scope of the name, instead of `Paste from Office` we could go with something like `Advanced Pasted`, `Advanced Content Pasted`, `Formatted Content Paste`, etc. Is is more generic, but blurs the meaning a little (that the plugin is designed to keep formatting when pasting from other text editors).

**Comment by wwalc** [comment]
Throwing some additional ideas:
 * `paste-from-external-apps`
 * `paste-content-cleaner`
 * `paste-beautifier`

`paste-from-office` sounds good too.

Btw. keep in mind that in all the documentation, project description and so on we will (hopefully) write good enough description what it does to cover all the keywords people may use to find it. So even if we don't find the most perfect name for it, the readme or documentation or whatever will fix it a bit.

**Comment by f1ames** [comment]
The `paste-from-external-apps` name is quite unattractive and boring, but it tells exactly what the plugin does which makes me undecided... 😝 

As there is more than one `Office` (MS Office, Libre Office, Open Office), `paste-from-office` may have broader meaning than only Microsoft Office for many people so its 👍 for me.

**Comment by Reinmar** [comment]
OK, 3 of us are ok with paste-from-office, so let's go this way. I'll rename the repo.

**Comment by Reinmar** [comment]
@f1ames I leave you renaming things in ths repo.

**Comment by f1ames** [comment]
Ok, closed in https://github.com/ckeditor/ckeditor5-paste-from-office/commit/37ae78befb44ba3c9060633edf0c10400ef043b9.
